version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/convo_data
      - PORT=5000
      - GROQ_API_KEY=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
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000

volumes:
  mongo_data:
   